name: release

on:
  push:
    tags: 
    - releases/[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag != '' && inputs.tag || github.ref }}

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Get the version
      id: get_version
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: './Directory.Build.props'
        xpath: '//Version'
    
    - name: Create short version
      id: shortversion
      run: |
        $version = "${{ steps.get_version.outputs.info }}".Substring(0, "${{ steps.get_version.outputs.info }}".LastIndexOf("."))
        Write-Host "::set-output name=shortversion::$version"
      shell: pwsh
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore -c Release .\Serilog.Enrichers.Sensitive.sln
    
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    
    - name: Create NuGet package for Serilog.Enrichers.Sensitive
      run: dotnet pack ./src/Serilog.Enrichers.Sensitive/Serilog.Enrichers.Sensitive.csproj -c Release --no-build --no-restore -o ./packaging
    
    - name: Get changelog
      id: get_changelog
      run: |
          ./get-changelog.ps1 -currentVersion "${{ steps.shortversion.outputs.shortversion }}"
      shell: pwsh
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: ./packaging/Serilog.Enrichers.Sensitive.${{ steps.shortversion.outputs.shortversion }}.nupkg
        tag_name: ${{ steps.get_version.outputs.info }}
        name: ${{ steps.get_version.outputs.info }}
        draft: false
        prerelease: false
        body_path: ./version-changelog.md
        make_latest: true
    
    - name: Publish enricher package to public NuGet repository
      run: dotnet nuget push -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json ./packaging/Serilog.Enrichers.Sensitive.${{ steps.shortversion.outputs.shortversion }}.nupkg --skip-duplicate --no-symbols
